pull_request_rules:
  - name: Approve and Merge Steward PRs on CI success
    conditions:
      - author=scala-steward
      - status-success="build"
      - body~=labels:.*semver-spec-patch
    actions:
      review:
        type: APPROVE
        message: Automatically approving scala-steward
      merge:
        method: merge